### ISSUE TITLE
question: How do you test your services with dependency injection?

### ISSUE THREAD

**Issue by buronix** [typestack/typedi#1055]
Im trying to test some global standalone classes injected in my code, Im new to Typedi, I really like it, but the lack of documentation is killing me.
My problem is mostly with testing, I see no example at all of how to test with typedi, not sure about you guys, but I just took as granted that some examples of how to test with jest (or whatever) will be present, and now I found that maybe I just lost a week cause there is no  example at all.
How do you test your injected dependencies?
By the way, not as manually parametrized, pls, I saw a lot of this in huge amount of helping places, not sure why, but If I could send my classes instances as parameters I will not need dependency injection at all.

**Comment by telega** [comment]
One approach is to use Container.set and Container.get in your tests. 

```
@Service()
class MyGlobalClass() {
  foo(){}
}

@Service()
class MyOtherClass( public global: MyGlobalClass) {}
```

Then in your test, you do

```
describe('MyOtherClass' , () => {
 it('tests the class', () =>{
 Container.set(MyGlobalClass, {  foo: jest.fn().mockReturnValue(true)}) 
 const otherClass = Container.get(MyOtherClass)
 expect(otherClass.global.foo()).toBe(true)
 })
})
```

**Comment by tomasz-szymanek** [comment]
I did exactly that and suddenly it stopped working:

```
Container.set('example-api-client', new TestApiClient())
const service = Container.get(ServiceUsingExampleApiClient)

console.log(service.exampleApiClient) // original service, not TestApiClient one set using container
```

I cannot get it to work, and it doesn't have any sense whatsoever to stop working on me like that

**Comment by telega** [comment]
how are you injecting ExampleApiClient into ServiceUsingExampleApiClient ?

**Comment by attilaorosz** [comment]
Could you create a repo with this? Its hard to see whats wrong without context.

**Comment by tomasz-szymanek** [comment]
I cannot publish code from my work, and this is not reproducible since it doesnt work in that one only case, for now I can say that I've tried using Service() via type, and named Service() syntax (Service('name-of-service')) along with @Inject('name-of-service') and it doesnt work in either way.

**Comment by tomasz-szymanek** [comment]
```
import 'reflect-metadata'
import { Service } from 'typedi'

@Service('pocket-api-client')
export class PocketApiClient {
  call = async (...args: any[]): Promise<any> => {
    console.log('CALL ORIGINAL')
    return { json: async () => Promise.resolve({ data: 'example', id: '123' }), ok: true }
  }
}
```

```
import 'reflect-metadata'
import { Inject, Service } from 'typedi'
import { PocketApiClient } from '../../../../lib/api-client/pocket-api-client'

...

@Service()
export class AddPocketSectionItem {
  @Inject('pocket-api-client')
  public pocketApiClient: PocketApiClient
  constructor() {}
  
  ...
```

```
import 'reflect-metadata'
import { Container } from 'typedi'
import { AddPocketSectionItem } from '../services/request'

...

class TestApiClient {
  public call = async (...args) => {
    console.log('CALL TEST')
    return { json: async () => Promise.resolve({ data: 'example', id: '123' }), ok: true }
  }
}

...

describe('POCKET SERVICE add-pocket-section-item', () => {
  it('responds with data fetched from api service', async () => {
    Container.set('pocket-api-client', new TestApiClient())
    const service = Container.get(AddPocketSectionItem)
    
    console.log(service.pocketApiClient) // original pocketApiClient, not TestApiClient
```

What is funny, is that when I remove type from Inject() statement, it says:
```
ServiceNotFoundError: Service with "pocket-api-client" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
```

Needless to say, I've tried using only Service() and type syntax, without names, and it doesn't work - injected value in AddPocketSectionItem is just undefined

**Comment by attilaorosz** [comment]
It's weird because it works for me locally. Is there a chance your lib is in a monorepo?

**Comment by tomasz-szymanek** [comment]
Yes, but other apps are not using any DI containers. It stopped working when I added some new code (unrelated to this), using httpContext for acquiring some headers from each request, and setting getConfig() method in a container via Container.set('get-config', getConfig). It's tested and mockable 

```
import { Config } from 'config'
import { Container } from 'typedi'
import { getConfig } from '../get-config'
import { mockedConfig } from './config-mock'

describe('getConfig method', () => {
  it('responds with generated config', async () => {
    const config = getConfig()

    expect(config).toEqual(mockedConfig)
  })

  it('responds with generated config while using default app name', async () => {
    const config = getConfig('moda')

    expect(config).toEqual(mockedConfig)
  })

  it('is injectable', async () => {
    Container.set('MOCK_GET_CONFIG', getConfig)
    const injectedConfig = Container.get('MOCK_GET_CONFIG') as () => Config
    const config = injectedConfig()

    expect(config).toEqual(mockedConfig)
  })
})
```

those tests are passing

**Comment by attilaorosz** [comment]
The problem is the metadata storage of the DI, technically it's tied to your node_modules folder. If your app happens to be in a monorepo that has separate node_module instances for each part, you are kinda out of luck. The Container instance will be different for each. Could you verify if that's the case?

**Comment by tomasz-szymanek** [comment]
First of all, thanks for your help, it's really kind of you. I verified, my API only uses one exclusive node_modules.

**Comment by attilaorosz** [comment]
> What is funny, is that when I remove type from Inject() statement, it says:

That is expected, if you never reference the class that registers the token it won't be available in the container.

> Needless to say, I've tried using only Service() and type syntax, without names, and it doesn't work - injected value in AddPocketSectionItem is just undefined

This is the more interesting part, because if the container is not able to find the token it should throw an error.
The troubling part is that if you mess up the mock registration in the test, it should return the original not undefined.

**Comment by tomasz-szymanek** [comment]
In test it returns mocked one, in service's body there is undefined, without error

**Comment by attilaorosz** [comment]
Do you use `@Inject` or constructor injection?

**Comment by tomasz-szymanek** [comment]
```
describe('POCKET SERVICE add-pocket-section-item', () => {
  it('responds with data fetched from api service', async () => {
    Container.set(PocketApiClient, new TestApiClient())
    const service = Container.get(AddPocketSectionItem)
    const mockedApiClient = Container.get(PocketApiClient)

    console.log(service.pocketApiClient) 
    console.log(mockedApiClient)
```

```
console.log
    undefined

      at console.log (../../node_modules/@sentry/src/integrations/console.ts:51:1)

  console.log
    TestApiClient { call: [Function (anonymous)] }

      at console.log (../../node_modules/@sentry/src/integrations/console.ts:51:1)
```

**Comment by tomasz-szymanek** [comment]
Tried both, and here's funny stuff

I moved `Container.set(GET_CONFIG, getConfig)` to separate middleware, and when I used constructor injection it started to work. Thanks, I think this conversation can be closed now.

**Comment by tomasz-szymanek** [comment]
Tried both, it still doesn't work (sorry, I got excited because test passed)

**Comment by attilaorosz** [comment]
Keep in mind that with `@Inject` you won't be able to access your injected dependency in the constructor body, the injection is done lazily

**Comment by tomasz-szymanek** [comment]
After using constructor injection (without @Inject() decorator) it just injects original dependency instead of mock:
```
Container.set(PocketApiClient, new TestApiClient())
    const service = Container.get(AddPocketSectionItem)
    const mockedApiClient = Container.get(PocketApiClient)

    console.log(service.pocketApiClient) // original pocketApiClient, not TestApiClient
    console.log(mockedApiClient)
```

```
console.log
    PocketApiClient { call: [Function (anonymous)] }

      at console.log (../../node_modules/@sentry/src/integrations/console.ts:51:1)

  console.log
    TestApiClient { call: [Function (anonymous)] }

      at console.log (../../node_modules/@sentry/src/integrations/console.ts:51:1)
```

**Comment by tomasz-szymanek** [comment]
```
@Service()
export class AddPocketSectionItem {
  constructor(public pocketApiClient: PocketApiClient) {}
  ```
  
  ```
  @Service()
export class PocketApiClient {
  call = async (...args: any[]): Promise<any> => {
    console.log('CALL ORIGINAL')
    return { json: async () => Promise.resolve({ data: 'example', id: '123' }), ok: true }
  }
}
  ```

**Comment by attilaorosz** [comment]
Do you clear your container after each test? It could be that the container instanciated your service already, so you setting the dependency of your service does nothing since `Container.get` will just get back the already created instance anyway.

**Comment by tomasz-szymanek** [comment]
That ought to be the case here! How do I clear container? I searched in documentation, and I didn't see anything like "reset"

**Comment by attilaorosz** [comment]
`Container.reset()` should do it for you

**Comment by tomasz-szymanek** [comment]
It doesn't work unfortunately, still getting original service instead of mocked one

**Comment by attilaorosz** [comment]
Just for the sake of the test, could you remove the `@Service` decorator from PocketApiClient and see what happens?

**Comment by tomasz-szymanek** [comment]
```
ServiceNotFoundError: Service with "MaybeConstructable<PocketApiClient>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
```

**Comment by attilaorosz** [comment]
Ok at this point all I can think of is that something else creates that service for you beforehand somewhere. Could you try to reset the container in the test itself before setting the mock?

**Comment by tomasz-szymanek** [comment]
Yeah, I've tried that with the same effect. No worries mate, I'm done for today anyways, tomorrow I will try some other ideas

Thank you so much

**Comment by attilaorosz** [comment]
You could add a log before the `Container.get` to make sure it's actually throwing there not beforehand

**Comment by tomasz-szymanek** [comment]
```
describe('POCKET SERVICE add-pocket-section-item', () => {
  it('responds with data fetched from api service', async () => {
    Container.reset()
    Container.set(PocketApiClient, new TestApiClient())
    const service = Container.get(AddPocketSectionItem)
    console.log(service.pocketApiClient)
    
    const mockedApiClient = Container.get(PocketApiClient)
    console.log(mockedApiClient)
```

its respectively `undefined` and `TestApiClient { call: [Function (anonymous)] }`

**Comment by attilaorosz** [comment]
pinging @NoNameProvided for additional ideas

**Comment by telega** [comment]
maybe as an experiment try changing the implementation of AddPocketSectionItem to 
```@Service()
export class AddPocketSectionItem {
  public pocketApiClient = Container.get(PocketApiClient)
  constructor() {}

**Comment by abhayshiravanthe** [comment]
See [this](https://github.com/typestack/typedi/issues/1084#issuecomment-1547886537)
and also, remove all manual mocks of injected dependencies in the test code. 
When asserting these injected class's methods in Jest tests, always use `jest.spyOn` instead of mocking them.

**Comment by Edkiri** [comment]
> One approach is to use Container.set and Container.get in your tests.
> 
> ```
> @Service()
> class MyGlobalClass() {
>   foo(){}
> }
> 
> @Service()
> class MyOtherClass( public global: MyGlobalClass) {}
> ```
> 
> Then in your test, you do
> 
> ```
> describe('MyOtherClass' , () => {
>  it('tests the class', () =>{
>  Container.set(MyGlobalClass, {  foo: jest.fn().mockReturnValue(true)}) 
>  const otherClass = Container.get(MyOtherClass)
>  expect(otherClass.global.foo()).toBe(true)
>  })
> })
> ```

It works for me! 
I was also missing the import 'reflect-metadata' in my test file.
