### ISSUE TITLE
fix: CannotInstantiateValueError when injecting document as part of DI

### ISSUE THREAD

**Issue by whtrbit** [typestack/typedi#196]
### Description
The goal is to make the `document` part of DI tree.
To achieve this I'm using `Token` like so:
```ts
// This file is loaded with Webpack before my application bootstrap
import 'reflect-metadata';
import { Container, Token } from 'typedi';

const tokenDocument: Token<Document> = new Token<Document>('document');

Container.set(tokenDocument, document);
```
And then inject like so:
```
export class MyClass  {
  constructor(
    @Inject(tokenDocument) private document: Document
  ) {}
}
```

### Expected behavior
No error. `document` is now injectable.

### Actual behavior
Error occurred:
```js
Uncaught CannotInstantiateValueError
    at new CannotInstantiateValueError (http://127.0.0.1:8888/index.umd.js:8480:28)
    at ContainerInstance.getServiceValue (http://127.0.0.1:8888/index.umd.js:7998:19)
    at ContainerInstance.get (http://127.0.0.1:8888/index.umd.js:7874:30)
    at Object.value (http://127.0.0.1:8888/index.umd.js:8321:42)
    at http://127.0.0.1:8888/index.umd.js:8083:37
    at Array.map (<anonymous>)
    at ContainerInstance.initializeParams (http://127.0.0.1:8888/index.umd.js:8067:27)
    at ContainerInstance.getServiceValue (http://127.0.0.1:8888/index.umd.js:8037:31)
    at ContainerInstance.get (http://127.0.0.1:8888/index.umd.js:7874:30)
    at http://127.0.0.1:8888/index.umd.js:8085:30
```

**Comment by NoNameProvided** [comment]
I cannot reproduce. (I had to add the `@Service` decorator to the class, otherwise correctly a ServiceNotFound errors is thrown.)

```ts
// my-class.class.sts
import { Inject, Service } from "typedi";
import { MY_TOKEN } from "./my-token.token";

@Service() // <- I have added this.
export class MyClass {
  constructor(@Inject(MY_TOKEN) private document: Document) {}
}
```

```ts
// tokens.constant.ts
import { Token } from "typedi";

export const MY_TOKEN: Token<Document> = new Token<Document>("document");
```

```ts
// index.ts (app entrypoint)
import "reflect-metadata";
import { Container } from "typedi";
import { MY_TOKEN } from "./tokens.constant";
import { MyClass } from "./my-class.class";

Container.set(MY_TOKEN, document);

const instance = Container.get(MyClass);

console.log(instance); // logs an instance of the class to the console
console.log(instance instanceof MyClass); // logs true to console
```

**Comment by whtrbit** [comment]
Ahh, yes. Missed `@Service` decorator during the copy-paste. Sorry for that.
Anyway, with the xample you provided, I couldn't make it work. I have found the solution though:
```
Container.set({
  id: tokenDocument,
  factory: () => document,
});
```
So, using the factory solved the issue.
