### ISSUE TITLE
[Solved] fix: Container.set() not working after build, works fine before build/compilation

### ISSUE THREAD

**Issue by tanmaymishu** [typestack/typedi#654]
### Description
I have a global middleware where I am trying to put some value to the container. It works when working within the dev environment but doesn't work after building the source and transpiling the .ts files into .js files.
**Minimal code-snippet showcasing the problem**
Let's say I have this middleware where I'm trying to set something to container:
```ts
@Service()
@Middleware({ type: 'before' })
export class SomeMiddleware implements ExpressMiddlewareInterface {
    async use(request: Request, response: Response, next: NextFunction): Promise<void> {
        Container.set('foo', 'bar');
        next();
    }
}
```
And a controller where I am trying to retrieve it
```ts
@Service()
@Controller()
export class FooController {
    @Post('/foo')
    async create(@Req() req: Request, @Res() res: Response<ApiResponse>) {
        console.log(Container.get<string>('foo'));
        return res.json({ message: 'Success' });
    }
}
```

Here's how I am registering the controllers and middleware in my app.ts file:
```ts
useExpressServer(app, {
  routePrefix: '/api/v1',
  controllers: [path.join(__dirname + '/controllers/api/v1/**/*.controller.*')],
  defaultErrorHandler: false,
  middlewares: [path.join(__dirname, '/middleware/global/*.middleware.ts')],
});
```

Here are my NPM scripts:
```json
"scripts": {
    "build": "tsc --project tsconfig.json && tscpaths -p tsconfig.json -s ./src -o ./dist",
    "dev": "ts-node-dev --respawn --transpile-only -r tsconfig-paths/register src/index.ts",
    "start": "node dist/index.js"
}
```
And the tsconfig.json file:
```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "moduleResolution": "node",
    "baseUrl": "./src",
    "paths": {
      "@/*": [
        "./*"
      ]
    },
    "rootDirs": [
      "./src"
    ],
    "typeRoots": [
      "./src/types",
      "node_modules/@types"
    ],
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```
When I run `yarn dev`, the key-value gets bound to the container and I see the appropriate value. But when I run `yarn build`, and then try to hit the endpoint I get the `ServiceNotFound` error.

### Expected behavior
The value `bar` is printed on the console.
### Actual behavior
```
ServiceNotFoundError: Service with "foo" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
    at ContainerInstance.get (/Users/tanmay/code/my-project/node_modules/typedi/cjs/container-instance.class.js:45:15)
    at Function.get (/Users/tanmay/code/my-project/node_modules/typedi/cjs/container.class.js:28:36)
    at FooController.create (/Users/tanmay/code/my-project/dist/controllers/api/v1/foo.controller.js:xx:xx)
    at ActionMetadata.callMethod (/Users/tanmay/code/my-project/node_modules/routing-controllers/cjs/metadata/ActionMetadata.js:91:48)
    at /Users/tanmay/code/my-project/node_modules/routing-controllers/cjs/RoutingControllers.js:96:34
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by tanmaymishu** [comment]
After spending nearly a day, I've realized that the way I am importing the middleware is wrong. Since I am only importing `.ts` file, it's not *supposed to* work after the build. Because there is no *.ts* file after the build. Changing this:

```ts
middlewares: [path.join(__dirname, '/middleware/global/*.middleware.ts')],
```
To this:

```ts
middlewares: [path.join(__dirname, '/middleware/global/*.middleware.*')],
```

Solves this problem.
