### ISSUE TITLE
question: Getting "Class constructor MyService cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by schematical** [typestack/typedi#710]
I am trying to inject a service that extends another base service and I am getting this error:

```
{
      "message": "Class constructor CropSpeciesService cannot be invoked without 'new'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listCropSpecies"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Class constructor CropSpeciesService cannot be invoked without 'new'",
            "    at Object.value (/home/user1a/WebstormProjects/gardenplanner-lambda/src/decorators/Inject.ts:42:34)",
            "    at /home/user1a/WebstormProjects/gardenplanner-lambda/src/ContainerInstance.ts:381:54",
            "    at Array.forEach (<anonymous>)",
            "    at ContainerInstance.applyPropertyHandlers (/home/user1a/WebstormProjects/gardenplanner-lambda/src/ContainerInstance.ts:376:28)",
            "    at ContainerInstance.getServiceValue (/home/user1a/WebstormProjects/gardenplanner-lambda/src/ContainerInstance.ts:343:18)",
            "    at ContainerInstance.get (/home/user1a/WebstormProjects/gardenplanner-lambda/src/ContainerInstance.ts:109:25)",
            "    at Function.Container.get (/home/user1a/WebstormProjects/gardenplanner-lambda/src/Container.ts:107:36)",
            "    at IOCContainer.getInstance (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/type-graphql/dist/utils/container.js:39:26)",
            "    at /home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/type-graphql/dist/resolvers/create.js:15:51",
            "    at field.resolve (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
            "    at resolveField (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/graphql/execution/execute.js:464:18)",
            "    at executeFields (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/graphql/execution/execute.js:292:18)",
            "    at executeOperation (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/graphql/execution/execute.js:236:122)",
            "    at executeImpl (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/graphql/execution/execute.js:116:14)",
            "    at Object.execute (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/graphql/execution/execute.js:60:35)",
            "    at /home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/apollo-server-core/src/requestPipeline.ts:571:22",
            "    at Generator.next (<anonymous>)",
            "    at /home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)",
            "    at execute (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/apollo-server-core/dist/requestPipeline.js:240:20)",
            "    at Object.<anonymous> (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/apollo-server-core/src/requestPipeline.ts:452:30)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/home/user1a/WebstormProjects/gardenplanner-lambda/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    }```


Constructor setup: 

```
@Service()
export class CropSpeciesService extends BaseService(CropSpecies){

    constructor(
        @Inject('CropSpeciesModel')
        private cropSpeciesModel
    ) {
        super();
    }
  ...   
 ```
 TS Config:
 ```{

  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "incremental": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "removeComments": true,
    "sourceMap": true,
    "target": "es2022",
    "outDir": "lib",
    "importHelpers": true,
    "skipLibCheck": true
  },
  "include": ["src/**/**.ts", "serverless.ts"],
  "exclude": [
    "node_modules/**/*",
    ".serverless/**/*",
    ".webpack/**/*",
    "_warmup/**/*",
    ".vscode/**/*"
  ],
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```
BaseService(No constructor):
```
    class BaseServiceClass<T> {
        @Inject(Entity.name + 'Model')
        private model: ReturnModelType<AnyParamConstructor<EntityT>, BeAnObject>;
        ...
```

 Relevant packages::
 
 ```
    "typedi": "^0.8.0",
    "serverless-webpack": "^5.7.0",
    "ts-loader": "^9.2.8",
    "ts-node": "^10.7.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.6.3"
```
I can catch it in the debugger but it looks like its getting injected correctly but I still get that error. Here is the stack from the debugger constructor. 
```
CropSpeciesService(), handler.js:240
ContainerInstance.getServiceValue(), ContainerInstance.ts:336
ContainerInstance.get(), ContainerInstance.ts:109
anonymous(), ContainerInstance.ts:358
ContainerInstance.initializeParams(), ContainerInstance.ts:352
ContainerInstance.getServiceValue(), ContainerInstance.ts:305
ContainerInstance.get(), ContainerInstance.ts:109
Container.get(), Container.ts:107
getInstance(), container.js:39
anonymous(), create.js:15
....
```
Edit 1:
I tracked it down to the `Inject` decorator, specifically this line ` identifier = typeOrName();`

```

function Inject(typeOrName) {
    return function (target, propertyName, index) {
        if (!typeOrName)
            typeOrName = function () { return Reflect.getMetadata("design:type", target, propertyName); };
        Container_1.Container.registerHandler({
            object: target,
            propertyName: propertyName,
            index: index,
            value: function (containerInstance) {
                var identifier;
                if (typeof typeOrName === "string") {
                    identifier = typeOrName;
                }
                else if (typeOrName instanceof Token_1.Token) {
                    identifier = typeOrName;
                }
                else {
                    identifier = typeOrName();
                }
                if (identifier === Object)
                    throw new CannotInjectError_1.CannotInjectError(target, propertyName);
                return containerInstance.get(identifier);
            }
        });
    };
}
exports.Inject = Inject;
```

Odd thing is this does not match what I am seeing in Git currently for that same file.

**Comment by schematical** [comment]
Well after 2 days of messing with this it seems I needed to update to v0.10.0 of typedi and use the name of the service NOT the service class it self. So instead of 
`@Inject(MyService)`
I switched to 
`@Inject(MyService.name)`
